/**
 * Category presets — one-click full configuration
 */
export const CATEGORY_PRESETS = {
  motivation: {
    label: 'Motivation',
    icon: '🔥',
    description: 'Discipline, success, mindset, hustle',
    visual_style: 'cinematic',
    caption_style: 'tiktok_bold',
    highlight_color: '#FF6B35',
    animation_style: 'pan_zoom',
    music_track: 'epic_cinematic',
    music_volume: 35,
    duration_target: '60s',
    resolution: '1080p',
  },
  storytelling: {
    label: 'Storytelling',
    icon: '📖',
    description: 'True crime, history, personal stories',
    visual_style: 'documentary',
    caption_style: 'sentence',
    highlight_color: '#A3E635',
    animation_style: 'fade',
    music_track: 'dramatic_orchestral',
    music_volume: 25,
    duration_target: '60s',
    resolution: '1080p',
  },
  facts: {
    label: 'Fun Facts',
    icon: '🧠',
    description: 'Mind-blowing discoveries, psychology',
    visual_style: 'cinematic',
    caption_style: 'highlight',
    highlight_color: '#38BDF8',
    animation_style: 'zoom_in',
    music_track: 'upbeat_corporate',
    music_volume: 20,
    duration_target: '30s',
    resolution: '1080p',
  },
  horror: {
    label: 'Horror / Creepy',
    icon: '👻',
    description: 'Scary stories, unsolved mysteries',
    visual_style: 'dark',
    caption_style: 'word_by_word',
    highlight_color: '#EF4444',
    animation_style: 'glitch',
    music_track: 'dark_ambient',
    music_volume: 30,
    duration_target: '60s',
    resolution: '1080p',
  },
  finance: {
    label: 'Finance',
    icon: '💰',
    description: 'Money tips, passive income, investing',
    visual_style: 'realistic',
    caption_style: 'tiktok_bold',
    highlight_color: '#34D399',
    animation_style: 'pan_zoom',
    music_track: 'lofi_chill',
    music_volume: 20,
    duration_target: '60s',
    resolution: '1080p',
  },
  fitness: {
    label: 'Fitness',
    icon: '💪',
    description: 'Workouts, transformation, health',
    visual_style: 'motivational',
    caption_style: 'tiktok_bold',
    highlight_color: '#F59E0B',
    animation_style: 'pan_zoom',
    music_track: 'epic_cinematic',
    music_volume: 35,
    duration_target: '30s',
    resolution: '1080p',
  },
  dark_psychology: {
    label: 'Dark Psychology',
    icon: '🌑',
    description: 'Manipulation, influence, mind control',
    visual_style: 'dark',
    caption_style: 'highlight',
    highlight_color: '#8B5CF6',
    animation_style: 'fade',
    music_track: 'dark_ambient',
    music_volume: 25,
    duration_target: '60s',
    resolution: '1080p',
  },
  self_improvement: {
    label: 'Self Improvement',
    icon: '🎯',
    description: 'Habits, discipline, personal growth',
    visual_style: 'cinematic',
    caption_style: 'sentence',
    highlight_color: '#A3E635',
    animation_style: 'pan_zoom',
    music_track: 'motivational_piano',
    music_volume: 22,
    duration_target: '60s',
    resolution: '1080p',
  },
  business: {
    label: 'Business Mindset',
    icon: '📈',
    description: 'Entrepreneurship, startups, leadership',
    visual_style: 'cinematic',
    caption_style: 'tiktok_bold',
    highlight_color: '#F59E0B',
    animation_style: 'pan_zoom',
    music_track: 'upbeat_corporate',
    music_volume: 20,
    duration_target: '60s',
    resolution: '1080p',
  },
  custom: {
    label: 'Custom',
    icon: '✨',
    description: 'Your own unique style',
    visual_style: 'cinematic',
    caption_style: 'tiktok_bold',
    highlight_color: '#A3E635',
    animation_style: 'pan_zoom',
    music_track: 'epic_cinematic',
    music_volume: 30,
    duration_target: '60s',
    resolution: '1080p',
  },
};

export const CATEGORIES = Object.entries(CATEGORY_PRESETS).map(([key, val]) => ({
  value: key,
  label: val.label,
  icon: val.icon,
  description: val.description,
}));